.TH GKAMUS 1 "FEB 14, 2011"
.SH NAME
gkamus \- Indonesian English dictionary
.SH SYNOPSIS
.B gkamus
.SH DESCRIPTION
.PP
\fBgkamus\fP Indonesian English dictionary.

.SH AUTHOR
gkamus was written by Ardhan Madras <ajhwb@knac.com>, Firmansyah <leonard_gimsong@yahoo.com>
.PP
This manual page was written by Mahyuddin Susanto <udienz@ubuntu.com>
for the Debian project (but may be used by others).
